# Generated by Django 3.2.4 on 2021-06-21 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('correo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Correo')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('motivo', models.CharField(max_length=20, verbose_name='Motivo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
