# Generated by Django 3.2.4 on 2021-06-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210621_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='motivo',
            field=models.CharField(max_length=150, verbose_name='Motivo'),
        ),
    ]
